import './style.css';
import './retro.css';
import './fonts.css';
import './about.css';
import './controls.css';
import './settings-danger.css';
import './dark.css';
import './native-dialog.css';
import { invoke, convertFileSrc } from '@tauri-apps/api/core';
import { open, save } from '@tauri-apps/plugin-dialog';
import { openUrl } from '@tauri-apps/plugin-opener';
import { getCurrentWindow } from '@tauri-apps/api/window';
import { homeDir } from '@tauri-apps/api/path';

type Lang = 'zh'|'en';
type AudioItem = {id:number;path:string;name:string;ext:string;library:string;description:string;duration:number;rating:number;artist:string;album:string;genre:string;year:string;tags:string;scanned_at:number;favorite:boolean;cat_id:string;category:string;sub_category:string;user_category:string;vendor_category:string;fx_name:string;creator_id:string;source_id:string;user_data:string;ucs_library:string;path_exists:boolean;library_exists:boolean};
type Library = {id:number;path:string;name:string;exists:boolean};
type ScanStatus = {running:boolean;phase:'idle'|'counting'|'scanning'|'completed'|'cancelled'|'error';current:number;total:number;path:string;message:string};
type Stats = {files:number;duration:number;libraries:number};
const zh = {title:'Lings',library:'音效库',addLibrary:'添加文件夹',rescan:'重新扫描',all:'全部音效',recent:'最近扫描',playlist:'播放列表',favorites:'收藏',search:'搜索文件名、UCS分类、标签、描述…',work:'工作目录',chooseWork:'选择目录',copy:'复制到工作目录',reveal:'在文件管理器中显示',info:'编辑信息',addPlaylist:'加入播放列表',removePlaylist:'移出播放列表',delete:'从索引移除',play:'播放',auto:'自动连播',empty:'添加一个音效文件夹来开始',scanning:'正在扫描…',files:'个文件',selected:'已选择',metadata:'UCS 元数据',save:'保存',cancel:'取消',description:'描述',rating:'评分',artist:'艺术家',album:'专辑',genre:'类型',year:'年份',tags:'关键词',path:'路径',filename:'文件名',type:'格式',duration:'时长',libraryCol:'音效库',lang:'EN',scanDone:'扫描完成',copied:'已复制到工作目录',confirmDelete:'仅从索引移除选中项目？原文件不会删除。',noneWork:'请先选择工作目录',scanError:'扫描失败',catId:'CatID',category:'分类',subCategory:'子分类',userCategory:'用户分类',vendorCategory:'厂商分类',fxName:'音效名称',creatorId:'CreatorID',sourceId:'SourceID',userData:'用户数据',ucsLibrary:'UCS 音效库',about:'关于',fontLicenses:'字体授权协议',officialPage:'打开官方页面',licenseLoadError:'无法加载授权文本'};
const en:typeof zh = {title:'Lings',library:'Libraries',addLibrary:'Add folder',rescan:'Rescan',all:'All sounds',recent:'Last scanned',playlist:'Playlist',favorites:'Favorites',search:'Search names, UCS categories, tags…',work:'Work folder',chooseWork:'Choose folder',copy:'Copy to work folder',reveal:'Reveal in file manager',info:'Edit info',addPlaylist:'Add to playlist',removePlaylist:'Remove from playlist',delete:'Remove from index',play:'Play',auto:'Auto play',empty:'Add a sound folder to begin',scanning:'Scanning…',files:'files',selected:'selected',metadata:'UCS Metadata',save:'Save',cancel:'Cancel',description:'Description',rating:'Rating',artist:'Artist',album:'Album',genre:'Genre',year:'Year',tags:'Keywords',path:'Path',filename:'File name',type:'Format',duration:'Duration',libraryCol:'Library',lang:'中',scanDone:'Scan complete',copied:'Copied to work folder',confirmDelete:'Remove selected items from the index? Original files stay untouched.',noneWork:'Choose a work folder first',scanError:'Scan failed',catId:'CatID',category:'Category',subCategory:'SubCategory',userCategory:'UserCategory',vendorCategory:'VendorCategory',fxName:'FXName',creatorId:'CreatorID',sourceId:'SourceID',userData:'UserData',ucsLibrary:'UCS Library',about:'About',fontLicenses:'Font licenses',officialPage:'Open official page',licenseLoadError:'Unable to load license text'};
let lang:Lang=(localStorage.lang as Lang)||'zh', t=lang==='zh'?zh:en;
let items:AudioItem[]=[], libraries:Library[]=[], selected=new Set<number>(), active:number|null=null, lastSelected:number|null=null, view='all', sortKey:keyof AudioItem='name', sortAsc=true, workFolder=localStorage.workFolder||'', autoPlay=false, scanStamp=0, scanLocked=localStorage.scanLocked==='true', scanRunning=false, scanCancelled=false, directoryDialogOpen=false;
const audio=new Audio(); audio.preload='metadata';
const app=document.querySelector<HTMLDivElement>('#app')!;
const fmt=(s:number)=>{if(!Number.isFinite(s))return '--:--'; const m=Math.floor(s/60),x=Math.floor(s%60);return `${m}:${String(x).padStart(2,'0')}`};
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const tr=(cn:string,en:string)=>lang==='zh'?cn:en;

function shell(){app.innerHTML=`<div class="window"><aside><div class="brand"><span class="brandmark">◉</span><b>${t.title}</b><button id="lang">${t.lang}</button></div><nav><button data-view="all" class="nav active">⌁ ${t.all}<span id="allCount">0</span></button><button data-view="recent" class="nav">◷ ${t.recent}</button><button data-view="playlist" class="nav">☷ ${t.playlist}</button><button data-view="favorites" class="nav">♡ ${t.favorites}</button></nav><div class="sideTitle"><span>${t.library}</span><button id="addLib" title="${t.addLibrary}">＋</button></div><div id="libraries"></div><button class="add" id="addLib2">＋ ${t.addLibrary}</button><div class="work"><small>${t.work}</small><div id="workPath">${esc(workFolder||t.chooseWork)}</div><button id="chooseWork">⌂ ${t.chooseWork}</button></div></aside><main><header><div class="search">⌕ <input id="search" placeholder="${t.search}"></div><button id="rescan">↻ ${t.rescan}</button><button id="edit" disabled>✎ ${t.info}</button><button id="copy" class="primary" disabled>⇩ ${t.copy}</button></header><div class="status"><span id="statusText">0 ${t.files}</span><div class="viewtabs"><button data-density="comfortable" class="active">▦</button><button data-density="compact">☷</button></div></div><section class="tableWrap"><table><thead><tr><th class="check"><input id="checkAll" type="checkbox"></th>${head('name',t.filename)}${head('ext',t.type)}${head('library',t.libraryCol)}${head('description',t.description)}${head('duration',t.duration)}${head('rating',t.rating)}</tr></thead><tbody id="rows"></tbody></table><div id="empty" class="empty"><div class="emptyIcon">♫</div><h2>${t.empty}</h2><button id="emptyAdd" class="primary">＋ ${t.addLibrary}</button></div></section><footer><button id="play" class="play">▶</button><div class="now"><b id="nowName">—</b><span id="nowMeta">—</span></div><span id="cur">0:00</span><input id="progress" type="range" min="0" max="1000" value="0"><span id="dur">0:00</span><button id="auto">↪ ${t.auto}</button><span>♩</span><input id="volume" type="range" min="0" max="1" step=".01" value="0.8"></footer></main></div><div id="toast"></div><dialog id="metadata"></dialog><div id="menu" class="menu"></div>`; bind(); renderLibraries(); render();}
function head(k:keyof AudioItem,label:string){return `<th data-sort="${k}">${label}<span></span></th>`}
function bind(){
 setupAbout();
 setupControls();
 const ucsHeader=document.querySelector<HTMLElement>('th[data-sort="library"]');if(ucsHeader){ucsHeader.dataset.sort='cat_id';ucsHeader.textContent=`${t.catId} / ${t.category}`}
 document.querySelector('#lang')!.addEventListener('click',()=>{lang=lang==='zh'?'en':'zh';localStorage.lang=lang;t=lang==='zh'?zh:en;shell()});
 ['#addLib','#addLib2','#emptyAdd'].forEach(s=>document.querySelector(s)?.addEventListener('click',addLibrary));
 document.querySelector('#chooseWork')!.addEventListener('click',chooseWork); document.querySelector('#rescan')!.addEventListener('click',rescan);
 document.querySelector('#search')!.addEventListener('input',render); document.querySelector('#copy')!.addEventListener('click',copySelected); document.querySelector('#edit')!.addEventListener('click',editSelected);
 document.querySelector('#play')!.addEventListener('click',togglePlay); document.querySelector('#auto')!.addEventListener('click',e=>{autoPlay=!autoPlay;(e.currentTarget as HTMLElement).classList.toggle('on',autoPlay)});
 const p=document.querySelector<HTMLInputElement>('#progress')!;p.addEventListener('input',()=>{if(audio.duration)audio.currentTime=+p.value/1000*audio.duration});
 const v=document.querySelector<HTMLInputElement>('#volume')!;audio.volume=+v.value;v.addEventListener('input',()=>audio.volume=+v.value);
 document.querySelector('#checkAll')!.addEventListener('change',e=>{selected.clear();if((e.target as HTMLInputElement).checked) filtered().forEach(x=>selected.add(x.id));render()});
 document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{view=(b as HTMLElement).dataset.view!;document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x===b));load()}));
 document.querySelectorAll('[data-sort]').forEach(h=>h.addEventListener('click',()=>{const k=(h as HTMLElement).dataset.sort as keyof AudioItem;if(sortKey===k)sortAsc=!sortAsc;else{sortKey=k;sortAsc=true}render()}));
 document.onpointerdown=e=>{const target=e.target as HTMLElement;if(!target.closest('.menu'))closeMenus()};
 document.onkeydown=e=>{if(e.code!=='Space'||e.repeat)return;const target=e.target as HTMLElement;if(target.closest('input,textarea,button,select,[contenteditable="true"],dialog'))return;const id=lastSelected!==null&&selected.has(lastSelected)?lastSelected:selected.size===1?[...selected][0]:null;if(id===null)return;e.preventDefault();playItem(id)};
}
function filtered(){const q=(document.querySelector<HTMLInputElement>('#search')?.value||'').trim().toLocaleLowerCase();return items.filter(x=>!q||[x.name,x.description,x.tags,x.library,x.cat_id,x.category,x.sub_category,x.user_category,x.vendor_category,x.fx_name,x.creator_id,x.source_id,x.user_data,x.ucs_library].some(v=>(v||'').toLocaleLowerCase().includes(q))).sort((a,b)=>{const x=a[sortKey],y=b[sortKey];const cmp=typeof x==='number'&&typeof y==='number'?x-y:String(x).localeCompare(String(y),lang==='zh'?'zh-CN':'en');return cmp*(sortAsc?1:-1)})}
function render(){const list=filtered(), body=document.querySelector('#rows');if(!body)return;document.querySelector('#empty')?.classList.toggle('show',!items.length);body.innerHTML=list.map(x=>`<tr data-id="${x.id}" class="${selected.has(x.id)?'selected':''} ${active===x.id?'active':''} ${!x.path_exists?'missing':''}"><td class="check"><input type="checkbox" ${selected.has(x.id)?'checked':''}></td><td><div class="file"><button class="miniPlay" ${!x.path_exists?'disabled':''}>${active===x.id&&!audio.paused?'■':'▶'}</button><span><b>${esc(x.fx_name||x.name)} ${!x.path_exists?`<i class="missingMark" title="${tr('文件不存在','File does not exist')}">?</i>`:''}</b><small>${esc(x.name)} · ${esc(x.path)}</small></span></div></td><td><span class="format">${esc(x.ext.toUpperCase())}</span></td><td>${x.cat_id?`<span class="ucsCat">${esc(x.cat_id)}</span> ${esc(x.category)}`:esc(x.library)}</td><td class="desc">${esc([x.sub_category,x.description||x.tags].filter(Boolean).join(' · ')||'—')}</td><td>${fmt(x.duration)}</td><td><span class="star">★</span> ${x.rating.toFixed(1)}</td></tr>`).join('');
 body.querySelectorAll('tr').forEach(tr=>{const id=+(tr as HTMLElement).dataset.id!;tr.addEventListener('click',e=>{lastSelected=id;if((e.target as HTMLElement).closest('.miniPlay')){playItem(id);return}if((e.target as HTMLElement).matches('input')){selected.has(id)?selected.delete(id):selected.add(id)}else{selected.clear();selected.add(id)}render()});tr.addEventListener('dblclick',()=>{lastSelected=id;playItem(id)});tr.addEventListener('contextmenu',e=>{e.preventDefault();lastSelected=id;if(!selected.has(id)){selected.clear();selected.add(id);render()}showMenu(e.clientX,e.clientY)})});
 const n=selected.size;document.querySelectorAll<HTMLButtonElement>('#copy,#edit').forEach(b=>b.disabled=!n);document.querySelector('#statusText')!.textContent=`${list.length} ${t.files}${n?` · ${n} ${t.selected}`:''}`;document.querySelector('#allCount')!.textContent=String(items.length);
}
function renderLibraries(){const box=document.querySelector('#libraries');if(!box)return;box.innerHTML=libraries.map(l=>`<button class="lib ${!l.exists?'missing':''}" data-lib-id="${l.id}" title="${esc(l.path)}"><span>▰</span><span>${esc(l.name)} ${!l.exists?`<i class="missingMark" title="${tr('文件夹不存在','Folder does not exist')}">?</i>`:''}<small>${esc(l.path)}</small></span></button>`).join('');box.querySelectorAll<HTMLElement>('.lib').forEach(el=>el.addEventListener('contextmenu',e=>{e.preventDefault();const lib=libraries.find(x=>x.id===+el.dataset.libId!);if(lib)showLibraryMenu(e.clientX,e.clientY,lib)}))}
function setupControls(){
 const header=document.querySelector('header'),rescanBtn=document.querySelector('#rescan');if(header&&rescanBtn&&!document.querySelector('#settingsBtn')){const b=document.createElement('button');b.id='settingsBtn';b.textContent='⚙';b.title=tr('设置','Settings');header.insertBefore(b,rescanBtn);b.addEventListener('click',showSettings)}
 const main=document.querySelector('main');if(main&&!document.querySelector('#scanPanel'))main.insertAdjacentHTML('beforeend',`<div id="scanPanel" class="scanPanel" hidden><div class="scanTop"><b id="scanTitle">${tr('正在扫描','Scanning')}</b><span id="scanNumbers">0 / 0</span><button id="cancelScan">■ ${tr('取消','Cancel')}</button></div><progress id="scanProgress" max="100" value="0"></progress><small id="scanPath">—</small></div>`);
 document.querySelector('#cancelScan')?.addEventListener('click',async()=>{scanCancelled=true;await invoke('cancel_scan');const b=document.querySelector<HTMLButtonElement>('#cancelScan');if(b){b.disabled=true;b.textContent=tr('正在取消…','Cancelling…')}});
 if(!document.querySelector('#interactionLock')){const lock=document.createElement('div');lock.id='interactionLock';lock.className='interactionLock';lock.hidden=true;document.body.appendChild(lock)}
 const volume=document.querySelector('#volume');const icon=volume?.previousElementSibling;if(icon){icon.textContent='🔊';icon.classList.add('volumeIcon')}
}
async function showSettings(){
 let d=document.querySelector<HTMLDialogElement>('#settingsDialog');if(!d){d=document.createElement('dialog');d.id='settingsDialog';document.body.appendChild(d)}
 d.innerHTML=`<div class="dialogHead"><h2>⚙ ${tr('设置','Settings')}</h2><button id="settingsClose">×</button></div><div class="settingsBody"><label class="settingRow"><span><b>${tr('扫描期间不允许其他操作','Block other actions while scanning')}</b><small>${tr('开启后，需要等待扫描完成或取消。','When enabled, wait for completion or cancel the scan.')}</small></span><input id="scanLockSetting" type="checkbox" ${scanLocked?'checked':''}></label><div class="settingRow"><span><b>${tr('数据库备份','Database backup')}</b><small>${tr('导出数据库，以便之后恢复数据。','Export the database for future recovery.')}</small></span><button id="exportDb">⇩ ${tr('导出数据库','Export database')}</button></div><div class="settingRow dangerRow"><span><b>${tr('清除扫描结果','Clear scan results')}</b><small>${tr('清除全部目录登记和数据库记录，不删除实际文件。','Remove all libraries and database records. Files on disk remain untouched.')}</small></span><button id="clearResults">× ${tr('清除','Clear')}</button></div></div>`;
 d.showModal();d.querySelector('#settingsClose')!.addEventListener('click',()=>d!.close());d.querySelector<HTMLInputElement>('#scanLockSetting')!.addEventListener('change',e=>{scanLocked=(e.target as HTMLInputElement).checked;localStorage.scanLocked=String(scanLocked);setScanLock(scanRunning)});d.querySelector('#exportDb')!.addEventListener('click',exportDatabase);d.querySelector('#clearResults')!.addEventListener('click',()=>clearScanResults(d!))
}
async function exportDatabase(){const destination=await save({title:tr('导出数据库','Export database'),defaultPath:`Lings-backup-${new Date().toISOString().slice(0,10)}.db`,filters:[{name:'SQLite database',extensions:['db']}]});if(!destination)return;try{await invoke('export_database',{destination:String(destination)});toast(tr('数据库已导出','Database exported'))}catch(e){toast(String(e))}}
async function clearScanResults(d:HTMLDialogElement){const ok=confirm(tr('确定清除所有扫描结果吗？\n\n这会删除全部目录登记、曲目索引、播放列表及数据库中的元数据，但不会删除任何实际文件。此操作无法撤销。','Clear all scan results?\n\nThis removes every library registration, track index, playlist, and database metadata. Files on disk will not be deleted. This cannot be undone.'));if(!ok)return;try{await invoke('clear_scan_results');audio.pause();audio.removeAttribute('src');active=null;lastSelected=null;selected.clear();items=[];libraries=[];scanRunning=false;setScanLock(false);d.close();await load();toast(tr('所有扫描结果已清除','All scan results cleared'))}catch(e){scanRunning=false;setScanLock(false);toast(String(e))}}
function setScanLock(running:boolean){const lock=document.querySelector<HTMLElement>('#interactionLock');if(lock)lock.hidden=!(running&&scanLocked);document.body.classList.toggle('scanLocked',running&&scanLocked)}
function updateScanUi(s:ScanStatus){const panel=document.querySelector<HTMLElement>('#scanPanel'),bar=document.querySelector<HTMLProgressElement>('#scanProgress'),numbers=document.querySelector('#scanNumbers'),path=document.querySelector('#scanPath'),title=document.querySelector('#scanTitle');if(!panel||!bar||!numbers||!path||!title)return;panel.hidden=!s.running;if(s.phase==='counting'){title.textContent=tr('正在统计音频文件…','Counting audio files…');bar.removeAttribute('value');numbers.textContent=String(s.current)}else{title.textContent=tr('正在扫描并读取元数据…','Scanning metadata…');bar.value=s.total?s.current/s.total*100:0;numbers.textContent=`${s.current} / ${s.total}`}path.textContent=s.path;scanRunning=s.running;setScanLock(s.running)}
function setupAbout(){
 const work=document.querySelector('.work');if(!work||document.querySelector('#aboutBtn'))return;
 work.insertAdjacentHTML('beforeend',`<button id="aboutBtn" class="aboutBtn">ⓘ ${t.about}</button>`);
 let d=document.querySelector<HTMLDialogElement>('#aboutDialog');if(!d){d=document.createElement('dialog');d.id='aboutDialog';document.body.appendChild(d)}
 document.querySelector('#aboutBtn')!.addEventListener('click',()=>showAbout(d));
}
async function showAbout(d:HTMLDialogElement){
 d.innerHTML=`<div class="aboutHero"><div class="aboutLogo">♫</div><div><h1>Lings</h1><b>VERSION 0.1.0</b></div><button id="aboutClose">×</button></div><p class="aboutSummary">Sound effects library manager · UCS 8.2.1</p><div class="fontNotice">Lings uses and embeds Cascadia Code and OPPO Sans 4.0.</div><h3>${t.fontLicenses}</h3><div class="licensePane"><div class="licenseLoading">LOADING…</div></div><div class="aboutLinks"><button data-url="https://github.com/microsoft/cascadia-code?tab=License-1-ov-file">Cascadia Code · ${t.officialPage} ↗</button><button data-url="https://www.coloros.com/article/A00000074/">OPPO Sans · ${t.officialPage} ↗</button></div>`;
 d.showModal();d.querySelector('#aboutClose')!.addEventListener('click',()=>d.close());d.querySelectorAll<HTMLElement>('[data-url]').forEach(b=>b.addEventListener('click',()=>openUrl(b.dataset.url!)));
 const pane=d.querySelector('.licensePane')!;try{const [c,o]=await Promise.all([fetch('/licenses/Cascadia-Code-OFL.txt').then(r=>r.text()),fetch('/licenses/OPPO-Sans-4.0-License-Notice.txt').then(r=>r.text())]);pane.innerHTML=`<section><h4>Cascadia Code — SIL Open Font License 1.1</h4><pre>${esc(c)}</pre></section><section><h4>OPPO Sans 4.0 — Font License Agreement</h4><pre>${esc(o)}</pre></section>`}catch{pane.textContent=t.licenseLoadError}
}
async function load(){try{items=await invoke('list_audio',{view});libraries=await invoke('list_libraries');renderLibraries();render()}catch(e){toast(String(e))}}
async function pickDirectory(title:string,defaultPath?:string){if(directoryDialogOpen)return null;directoryDialogOpen=true;const buttons=[...document.querySelectorAll<HTMLButtonElement>('#addLib,#addLib2,#emptyAdd,#chooseWork')];buttons.forEach(b=>b.disabled=true);document.body.classList.add('nativeDialogOpen');try{const start=defaultPath||await homeDir();return await open({directory:true,multiple:false,title,defaultPath:start})}catch(e){toast(String(e));return null}finally{directoryDialogOpen=false;buttons.forEach(b=>b.disabled=false);document.body.classList.remove('nativeDialogOpen');await getCurrentWindow().setFocus().catch(()=>{})}}
async function addLibrary(){const start=libraries.find(l=>l.exists)?.path;const path=await pickDirectory(t.addLibrary,start);if(!path)return;await scan(String(path))}
async function runOneScan(path:string){await invoke('start_scan',{path});for(;;){const s=await invoke<ScanStatus>('get_scan_status');updateScanUi(s);if(!s.running)return s;await new Promise(r=>setTimeout(r,120))}}
async function scan(path:string){scanStamp=Date.now();scanCancelled=false;try{const s=await runOneScan(path);if(s.phase==='completed'){await load();toast(`${t.scanDone}: ${s.message} ${t.files}`)}else if(s.phase==='cancelled'){toast(tr('扫描已取消，数据库未改变','Scan cancelled; database unchanged'))}else{toast(`${t.scanError}: ${s.message}`)}}catch(e){toast(`${t.scanError}: ${e}`)}finally{scanRunning=false;setScanLock(false);const panel=document.querySelector<HTMLElement>('#scanPanel');if(panel)panel.hidden=true}}
async function rescan(){if(!libraries.length)return addLibrary();scanCancelled=false;try{for(const l of libraries){if(scanCancelled)break;const s=await runOneScan(l.path);if(s.phase==='cancelled'){scanCancelled=true;toast(tr('扫描已取消，当前目录未改变','Scan cancelled; current library unchanged'));break}if(s.phase==='error'){toast(`${t.scanError}: ${s.message}`);break}}if(!scanCancelled){await load();toast(t.scanDone)}}catch(e){toast(`${t.scanError}: ${e}`)}finally{scanRunning=false;setScanLock(false);const panel=document.querySelector<HTMLElement>('#scanPanel');if(panel)panel.hidden=true}}
async function chooseWork(){const p=await pickDirectory(t.chooseWork,libraries.find(l=>l.exists)?.path);if(p){workFolder=String(p);localStorage.workFolder=workFolder;document.querySelector('#workPath')!.textContent=workFolder}}
async function copySelected(){if(!workFolder){toast(t.noneWork);return}await invoke('copy_files',{ids:[...selected],destination:workFolder});toast(t.copied)}
async function reveal(){const id=[...selected][0];if(id)await invoke('reveal_file',{id})}
async function remove(){if(!confirm(t.confirmDelete))return;await invoke('remove_from_index',{ids:[...selected]});selected.clear();await load()}
async function playlist(add:boolean){await invoke('set_playlist',{ids:[...selected],value:add});if(view==='playlist')await load();else toast(add?t.addPlaylist:t.removePlaylist)}
function closeMenus(){document.querySelectorAll('.menu.show').forEach(x=>x.classList.remove('show'))}
function menuAction(m:HTMLElement,selector:string,action:()=>void|Promise<void>){m.querySelector(selector)?.addEventListener('click',async e=>{e.stopPropagation();closeMenus();await action()})}
function positionMenu(m:HTMLElement,x:number,y:number){m.classList.add('show');const w=m.offsetWidth,h=m.offsetHeight;m.style.left=`${Math.max(6,Math.min(x,innerWidth-w-6))}px`;m.style.top=`${Math.max(6,Math.min(y,innerHeight-h-6))}px`}
function showMenu(x:number,y:number){const m=document.querySelector<HTMLElement>('#menu')!;m.innerHTML=`<button id="mInfo">✎ ${t.info}</button><button id="mReveal">⌕ ${t.reveal}</button><button id="mCopy">⇩ ${t.copy}</button><hr><button id="mAdd">＋ ${t.addPlaylist}</button><button id="mRemove">− ${t.removePlaylist}</button><hr><button id="mDelete" class="danger">× ${t.delete}</button>`;positionMenu(m,x,y);menuAction(m,'#mInfo',editSelected);menuAction(m,'#mReveal',reveal);menuAction(m,'#mCopy',copySelected);menuAction(m,'#mAdd',()=>playlist(true));menuAction(m,'#mRemove',()=>playlist(false));menuAction(m,'#mDelete',remove)}
function showLibraryMenu(x:number,y:number,lib:Library){const m=document.querySelector<HTMLElement>('#menu')!;m.innerHTML=`<div class="menuLabel">${esc(lib.name)}</div><button id="mRescan">↻ ${tr('扫描此目录','Scan this folder')}</button><hr><button id="mDeleteLibrary" class="danger">× ${tr('删除目录登记','Remove library')}</button>`;positionMenu(m,x,y);menuAction(m,'#mRescan',()=>scan(lib.path));menuAction(m,'#mDeleteLibrary',()=>deleteLibrary(lib))}
async function deleteLibrary(lib:Library){if(!confirm(tr(`确认删除目录“${lib.name}”的登记及其数据库记录？\n实际文件不会被删除。`,`Remove “${lib.name}” and its database records?\nFiles on disk will not be deleted.`)))return;await invoke('remove_library',{id:lib.id});selected.clear();await load();toast(tr('目录登记已删除','Library removed'))}
function editSelected(){const x=items.find(i=>i.id===[...selected][0]);if(!x)return;const d=document.querySelector<HTMLDialogElement>('#metadata')!;const field=(name:string,label:string,value:string)=>`<label>${label}<input name="${name}" value="${esc(value)}"></label>`;d.innerHTML=`<form method="dialog"><div class="dialogHead"><h2>${t.metadata}</h2><button value="cancel">×</button></div><div class="fileHero"><span>♫</span><div><b>${esc(x.fx_name||x.name)}</b><small>${esc(x.path)}</small></div></div><div class="ucsBadge">UCS 8.2.1 · iXML / ASWG</div><div class="grid ucsGrid">${field('cat_id',t.catId,x.cat_id)}${field('category',t.category,x.category)}${field('sub_category',t.subCategory,x.sub_category)}${field('fx_name',t.fxName,x.fx_name)}${field('user_category',t.userCategory,x.user_category)}${field('vendor_category',t.vendorCategory,x.vendor_category)}${field('creator_id',t.creatorId,x.creator_id)}${field('source_id',t.sourceId,x.source_id)}${field('ucs_library',t.ucsLibrary,x.ucs_library)}${field('user_data',t.userData,x.user_data)}</div><label>${t.description}<textarea name="description">${esc(x.description)}</textarea></label><div class="grid">${field('tags',t.tags,x.tags)}<label>${t.rating}<input name="rating" type="number" min="0" max="5" step=".5" value="${x.rating}"></label></div><div class="dialogActions"><button value="cancel">${t.cancel}</button><button value="default" class="primary">${t.save}</button></div></form>`;d.showModal();d.querySelector('form')!.addEventListener('submit',async e=>{if((e.submitter as HTMLButtonElement)?.value==='cancel')return;e.preventDefault();const f=new FormData(e.currentTarget as HTMLFormElement);await invoke('update_metadata',{id:x.id,metadata:Object.fromEntries(f)});d.close();await load();toast(t.save)})}
function playItem(id:number){const x=items.find(i=>i.id===id);if(!x)return;if(!x.path_exists){toast(tr('文件不存在','File does not exist'));return}if(active===id&&!audio.paused){audio.pause();render();return}active=id;audio.src=convertFileSrc(x.path);audio.play().catch(e=>toast(String(e)));document.querySelector('#nowName')!.textContent=x.name;document.querySelector('#nowMeta')!.textContent=`${x.ext.toUpperCase()} · ${x.library}`;render()}
function togglePlay(){if(active===null&&items.length)return playItem(items[0].id);audio.paused?audio.play():audio.pause()}
audio.addEventListener('play',()=>{const b=document.querySelector('#play');if(b)b.textContent='❚❚';render()});audio.addEventListener('pause',()=>{const b=document.querySelector('#play');if(b)b.textContent='▶';render()});audio.addEventListener('timeupdate',()=>{const p=document.querySelector<HTMLInputElement>('#progress');if(p)p.value=String(audio.duration?audio.currentTime/audio.duration*1000:0);const c=document.querySelector('#cur'),d=document.querySelector('#dur');if(c)c.textContent=fmt(audio.currentTime);if(d)d.textContent=fmt(audio.duration)});audio.addEventListener('ended',()=>{if(autoPlay&&active!==null){const list=filtered(),i=list.findIndex(x=>x.id===active);if(list[i+1])playItem(list[i+1].id)}});
function toast(msg:string,persist=false){const el=document.querySelector('#toast')!;el.textContent=msg;el.classList.add('show');if(!persist)setTimeout(()=>el.classList.remove('show'),2600)}
shell();load();
